name: Build armv6 toolchain
on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: armv6l_config
    - uses: actions/checkout@v3
      with:
        repository: crosstool-ng/crosstool-ng
        path: ctng-src
        ref: crosstool-ng-1.25.0
    - name: Prepare filesystem
      run: |
        mkdir crosstool-ng
        mkdir build
        mkdir build/dist
        mkdir build/archives
        mkdir build/.build
    - name: Build crosstool-ng
      run: |
        sudo apt-get install -y gperf help2man libtool-bin meson ninja-build
        cd ctng-src
        ./bootstrap
        ./configure --prefix=$GITHUB_WORKSPACE/crosstool-ng
        make
        make install
        echo "$GITHUB_WORKSPACE/crosstool-ng/bin" >> $GITHUB_PATH
    - name: Build Toolchain
      run: |
        cd $GITHUB_WORKSPACE/armv6l_config
        ct-ng build -j $(($(nproc) - 1))
        cd $GITHUB_WORKSPACE/build/dist/
        tar -czf arm-unknown-linux-gnueabihf-x86_64-ubuntu.tar.gz arm-unknown-linux-gnueabihf
        sha256sum arm-unknown-linux-gnueabihf-x86_64-ubuntu.tar.gz | tee arm-unknown-linux-gnueabihf-x86_64-ubuntu.tar.gz.sha256
    - name: Upload Toolchain Artifact
      uses: actions/upload-artifact@v3
      with:
        name: armv6l-tools
        path: ${{ github.workspace }}/build/dist/arm-unknown-linux-gnueabihf-x86_64-ubuntu.tar.gz
        if-no-files-found: error
    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      if: "startsWith(github.ref, 'refs/tags/')"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/build/dist/arm-unknown-linux-gnueabihf-x86_64-ubuntu.tar.gz*
        file_glob: true
        tag: ${{ github.ref }}
